#!/bin/bash

BASIC_CYAN="\e[0;36m"
BASIC_GREEN="\e[0;32m"
BASIC_RED="\e[0;31m"
ENDCOLOR="\e[0m"

echo -e "${BASIC_CYAN}Running unit tests before push...${ENDCOLOR}"
npm run test

if [[ $? -ne 0 ]]; then
  echo -e "${BASIC_RED}Tests failed! Push aborted.${ENDCOLOR}"
  exit 1
fi

echo -e "${BASIC_GREEN}All tests passed! Proceeding with push.${ENDCOLOR}"
